global:
    backup_destination_root: "/home/james/git_backup" # where to put all the backup files
  
  authentication: # note: they are matched from top to bottom
    - matches: 
        # - '^https://github.com/' # doesn't work for now
        - '^https://api.github.com/'
      username: 'username'
      password: 'password-or-apikey'
    # doesn't work for now
    # - matches:
    #     - '^git@github.com:'
    #   ssh_key: '/home/james/.ssh/id_rsa'
  
  directories:
    - provider: 'null' # does not do any processing
      repos:
        - "https://github.com/Jamesits/umbrella.git"
      
    - provider: 'GitHub'
      api_endpoint: 'https://api.github.com'
      searches:
        - "/orgs/empty-repo/repos?type=all" # all the repos of an organization
        - "/users/octocat?type=all" # all the repos of an user
        - "/user/repos?type=all" # all the repos that I have explicit permission to
